### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by DrewDogComputers** [james-tate/SRET#2]
What state is this project in? any unsurmountable roadblocks or the original author just not have the time? Whats finished and what needs doing still?

**Comment by james-tate** [comment]
Hi DrewDog. Thanks for the question. Yeah, so it turns out the company I work for really liked the idea behind this project and decided to fund it for our team's use internally. So, a of fully developed version of SRET does exist in the world. But, I am unable to release it or provide very many more details about it right now. The project you see here was in the very very early development stages. Unfortunately, for me to continue working on something similar open source would be a conflict of interest at-the-moment. If you might be interested in purchasing one email me and we might be able to work something out, thejamestate@gmail.com.
